import { Entity, IEntityList } from "../../infrastructure";
import { Card } from "./cards/card";
import { IDeck } from "./deck.interface";
export declare abstract class Deck extends Entity implements IDeck {
    protected _cards: IEntityList<Card>;
    abstract get name(): string;
    private _unplayedCards;
    get unplayedCards(): Array<Card>;
    private _playedCards;
    get playedCards(): Array<Card>;
    private _handCards;
    get handCards(): Array<Card>;
    private _discardedCards;
    get discardedCards(): Array<Card>;
    private _selectedCards;
    get selectedCards(): Card[];
    private _lastPlayedCards;
    get lastPlayedCards(): Array<Card>;
    private _handCardsNumber;
    private _maxSelectedCardsNumber;
    get playablesHands(): number;
    get playablesDiscards(): number;
    protected constructor(handCardsNumber: number, maxSelectedCardsNumber: number);
    init(): void;
    shuffle(): void;
    takeCardsToHand(): void;
    selectCard(card: Card): void;
    discardSelectedCards(): void;
    playSelectedCards(): void;
    changeHandCardsNumber(handCardsNumber: number): void;
    changeMaxSelectedCardsNumber(maxSelectedCardsNumber: number): void;
}
